import type { Metadata } from "next";
import { useLocale } from "next-intl";
import { Urbanist } from "next/font/google";
import { notFound } from "next/navigation";
import { ReactNode } from "react";

import "../globals.css";

const appFont = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "800"],
});

export const metadata: Metadata = {
  title: "Influencer Collab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: any;
}) {
  const locale = useLocale();

  if (locale !== params.locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={appFont.className}>
        <div>This is root layout</div>
        {children}
      </body>
    </html>
  );
}
